CATEGORIE = {
    1: 'Film TV e programmi',
    2: 'Musica',
    3: 'E Books',
    4: 'Film',
    6: 'Linux',
    7: 'Anime',
    8: 'Cartoni',
    9: 'Macintosh',
    10: 'Windows Software',
    11: 'Pc Game',
    12: 'Playstation',
    13: 'Students Releases',
    14: 'Documentari',
    21: 'Video Musicali',
    22: 'Sport',
    23: 'Teatro',
    24: 'Wrestling',
    25: 'Varie',
    26: 'Xbox',
    27: 'Immagini sfondi',
    28: 'Altri Giochi',
    29: 'Serie TV',
    30: 'Fumetteria',
    31: 'Trash',
    32: 'Nintendo',
    34: 'A Book',
    35: 'Podc: st',
    36: 'Edicola',
    37: 'Mobile'
}
